#!/usr/bin/env python3
"""Deterministic standalone design renderer, NOT the Study_Skills v2 certified pipeline."""
import json
from pathlib import Path
from html import escape as e

ROOT = Path(__file__).resolve().parent
models = json.loads((ROOT/'figure-models.json').read_text())
flow = models['pipeline']
refill = models['refill']
font = 'font-family="Noto Sans CJK SC,Arial,sans-serif"'

parts = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1150 150" role="img" aria-labelledby="title" {font}><title id="title">{e(flow["question"])}</title>']
for i, step in enumerate(flow['steps']):
    x = i*232
    parts.append(f'<rect x="{x+1}" y="20" width="217" height="108" rx="9" fill="#f4f7fa" stroke="#ced8e2"/><text x="{x+15}" y="48" font-size="13" fill="#516879">0{i+1}</text><text x="{x+15}" y="76" font-size="20" fill="#162e40">{e(step["title"])}</text>')
    # Fixed known model text is split at semantic separators, never truncated.
    label = step['detail'].split(' · ')
    lines = [' · '.join(label[:2]), ' · '.join(label[2:])] if len(label)>2 else [step['detail']]
    if len(lines[0]) > 12:
        text = lines[0]; lines = [text[:12], text[12:]]
    for j, line in enumerate(lines):
        parts.append(f'<text x="{x+15}" y="{101+j*19}" font-size="15" fill="#526775">{e(line)}</text>')
    if i<4:
        parts.append(f'<text x="{x+218}" y="81" font-size="19" fill="#688399">→</text>')
parts.append('</svg>')
flow_svg = ''.join(parts)
(ROOT/'evidence-flow.svg').write_text(flow_svg)
B = refill['capacity']; before = B*refill['before_fraction']; after = B*refill['after_fraction']
gain = after-before
refill_svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1040 230" role="img" aria-labelledby="title" {font}><title id="title">{e(refill['question'])}</title>
<text x="10" y="36" font-size="19" fill="#183247">重置前</text><rect x="120" y="14" width="620" height="38" rx="4" fill="#edf1f4"/><rect x="120" y="14" width="{620*refill['before_fraction']}" height="38" rx="4" fill="#426a87"/><text x="766" y="39" font-size="20" fill="#183247">{before:.0f} / {B}</text>
<text x="10" y="111" font-size="19" fill="#183247">重置后</text><rect x="120" y="89" width="620" height="38" rx="4" fill="#edf1f4"/><rect x="120" y="89" width="{620*refill['before_fraction']}" height="38" fill="#426a87"/><rect x="{120+620*refill['before_fraction']}" y="89" width="{620*(refill['after_fraction']-refill['before_fraction'])}" height="38" fill="#b88632"/><text x="766" y="114" font-size="20" fill="#183247">{after:.0f} / {B}</text>
<rect x="120" y="164" width="15" height="15" fill="#426a87"/><text x="145" y="178" font-size="16" fill="#183247">原有未消费量</text><rect x="340" y="164" width="15" height="15" fill="#b88632"/><text x="365" y="178" font-size="16" fill="#183247">本次新增 {gain:.0f}（{gain/B:.0%}）</text><text x="120" y="212" font-size="15" fill="#526775">单位：{e(refill['unit'])}；假设满额容量 = {B}。不是账户实测值。</text></svg>'''
(ROOT/'refill-net-gain.svg').write_text(refill_svg)
mobile_flow = ''.join(f'<li><strong>{e(s["title"])}</strong><p>{e(s["detail"])}</p></li>' for s in flow['steps'])
html = '''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>成本工作台 · 设计研究</title>
<style>
:root{--ink:#173247;--muted:#586d7b;--line:#dbe3e8;--bg:#f4f6f8;--accent:#25586c;--warn:#8b6026}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:16px/1.6 "Noto Sans CJK SC",system-ui,sans-serif}a{color:var(--accent)}header{background:#173247;color:white;padding:24px max(24px,calc((100vw - 1200px)/2))}header small{color:#bed0dd}h1{margin:3px 0;font-size:30px;letter-spacing:.02em}main{max-width:1248px;margin:auto;padding:24px}h2{font-size:23px;margin:0 0 8px}h3{font-size:18px;margin:0 0 8px}p{margin:8px 0}.muted{color:var(--muted)}.banner{border:1px solid #dcc696;background:#fbf5e8;color:#705322;padding:14px 18px;border-radius:8px;margin-bottom:22px}.badge{display:inline-block;font-size:13px;padding:3px 9px;border-radius:4px;background:#e5edf1;color:#335b70}.warning{background:#fbf0d8;color:#805a24}.grid{display:grid;gap:16px;grid-template-columns:repeat(4,1fr)}.card,section{background:white;border:1px solid var(--line);border-radius:9px;padding:22px}.card strong{display:block;font-size:25px;margin:8px 0}.card small{color:var(--muted)}section{margin-top:22px}.two{display:grid;grid-template-columns:1fr 1fr;gap:22px}.scroll{overflow:auto}table{width:100%;border-collapse:collapse;min-width:680px;font-size:15px}th{text-align:left;font-weight:600;background:#f3f6f8}th,td{padding:12px;border-bottom:1px solid var(--line)}.form{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:16px}label{display:block;font-size:14px;color:var(--muted)}input,select,button{font:inherit;width:100%;padding:9px;border:1px solid #c8d3db;border-radius:5px;background:white;color:var(--ink)}button{background:var(--accent);color:white;cursor:pointer}.result{background:#eff5f7;border-left:4px solid var(--accent);padding:15px;margin-top:18px}.result strong{font-size:28px}.svgbox svg{width:100%;height:auto;display:block}.mobile-flow{display:none}.notes{font-size:14px;color:var(--muted)}footer{padding:28px 0;font-size:14px}.mini{font-size:13px}.tagline{display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap}.statline{font-size:17px;font-weight:600}.refill-mobile{display:none}
@media(max-width:800px){.grid{grid-template-columns:1fr 1fr}.two{grid-template-columns:1fr}.form{grid-template-columns:1fr 1fr}.flow-svg{display:none}.mobile-flow{display:block;padding-left:22px}.mobile-flow li{margin:15px 0}.mobile-flow p{margin:0}.refill-svg{display:none}.refill-mobile{display:block}main{padding:14px}section,.card{padding:18px}header{padding:20px}h1{font-size:26px}}
@media(max-width:400px){.grid,.form{grid-template-columns:1fr}h2{font-size:21px}}
@media print{body{background:white}header{background:white;color:var(--ink);padding:0}header small{color:var(--muted)}main{padding:0}.form,button{display:none}.grid{grid-template-columns:1fr 1fr}.flow-svg{display:none}.mobile-flow{display:block}.scroll{overflow:visible}table{min-width:0;font-size:12px}section{break-inside:avoid}a{color:inherit}}
</style></head><body><header><small>SUB2API / ADMIN / COST RESEARCH</small><div class="tagline"><h1>成本工作台</h1><span>2026-09-16 · 设计稿</span></div><p>先看实际支出，再看可交付量；把预测与账本分开。</p></header><main>
<div class="banner"><strong>尚未接入现网数据。</strong> 此页是可交互设计示意，不会充值、兑换重置卡、购买套餐或修改价格。公开额度来自旧快照；所有计算器参数均为模拟假设。</div>
<div class="grid"><div class="card"><span>本期实际成本</span><strong>待录入</strong><small>采购凭据 + 服务期间费用</small></div><div class="card"><span>服务器流量</span><strong>待采样</strong><small>vnStat / 云账单双重校验</small></div><div class="card"><span>自身有效周容量</span><strong>待校准</strong><small>不是站点挂牌 API 等值额度</small></div><div class="card"><span>可信成本报价</span><strong>尚不可给出</strong><small>缺采购账与自身观察历史</small></div></div>
<section><div class="tagline"><h2>01 · 数据是否足够支撑一个价格？</h2><span class="badge warning">公开证据 ≠ 实测成本</span></div><div class="scroll"><table><thead><tr><th>数据</th><th>目前读到的内容</th><th>来源与时间</th><th>处理</th></tr></thead><tbody><tr><td>20x Pro 周额度</td><td>$1,649.72 旧 API 等值量</td><td>Radar · 8月9日19:49</td><td>过期参考，不作为实时值</td></tr><tr><td>5x Pro / Plus</td><td>$412.43 / $82.49</td><td>Radar 自身推算</td><td>非独立账户实测</td></tr><tr><td>GPT-6 / Sol 分模型周量</td><td>未获取可靠明细</td><td>动态数据需进一步验证</td><td>保留空值</td></tr><tr><td>七日均值 / 两个月重置率</td><td>缺完整时间序列</td><td>32 为全历史事件数</td><td>不做伪平均</td></tr><tr><td>自身账本与配额</td><td>未连接</td><td>需授权的后台与采购记录</td><td>不生成真实后验</td></tr></tbody></table></div></section>
<section><h2>02 · @@FLOW_TITLE@@</h2><p class="muted">@@FLOW_ORDER@@</p><div class="svgbox flow-svg">@@FLOW@@</div><ol class="mobile-flow">@@MOBILE@@</ol><p class="statline">@@FLOW_TAKEAWAY@@</p><p class="notes">边界：@@FLOW_BOUNDARY@@</p></section>
<section><h2>03 · @@REFILL_TITLE@@</h2><p class="muted">比较同一预算池。这里假设满额为 1,000 单位，重置期间没有其他消费。</p><div class="svgbox refill-svg">@@REFILL@@</div><div class="refill-mobile"><p><strong>重置前：</strong>剩余800 / 1000（80%）。</p><p><strong>重置后：</strong>剩余1000 / 1000（100%）。</p><p><strong>本次真正增加：</strong>200 / 1000（20%）。</p></div><p class="statline">@@REFILL_TAKEAWAY@@</p><p class="notes">@@REFILL_BOUNDARY@@ 观察到的余量是数据；结合先验估计出的参数分布才是后验。</p></section>
<section id="sim"><div class="tagline"><h2>04 · 利用率与重置怎样影响成本？</h2><span class="badge warning">历史快照敏感性演算 · 非真实成本</span></div><p>美元仅作为此处的模拟现金币种。容量沿用旧 Radar 标称等值量，不能直接换算成当前 token 单价。</p><div class="form"><label>参考档位<select id="tier"><option value="pro">Pro 20x</option><option value="pro5">Pro 5x</option><option value="plus">Plus（沙盘中转）</option></select></label><label>本期订阅现金 / USD<input id="cash" type="number" value="200" min="0" step="1"></label><label>账期天数<input id="days" type="number" value="30" min="1" max="366"></label><label>每周基础量 / 旧参考量<input id="base" type="number" value="1649.72" min="0" step=".01"></label><label>有用交付利用率 / %<input id="use" type="number" value="50" min="0" max="100"></label><label>每周额外已生效重置次数<input id="events" type="number" value="0" min="0" step=".1"></label><label>重置前平均剩余 / %<input id="remain" type="number" value="80" min="0" max="100"></label><label>本期固定分摊 / USD<input id="fixed" type="number" value="0" min="0" step=".01"></label><label>本期已核价网络等变动费 / USD<input id="net" type="number" value="0" min="0" step=".01"></label></div><div class="result" aria-live="polite"><span>模拟现金成本 / 1 单位旧 Radar API 等值量</span><br><strong id="unit">0.0566 USD</strong><p id="detail">模拟本期有效量 3,535.11；成本200.00 USD。不是每百万token价格。</p></div><p class="notes">公式：(订阅 + 固定分摊 + 网络等费用) / [天数÷7 × 基础周量 × 利用率 × (1 + 额外重置次数 × (1−重置前余量))]。只在同容量、满额重置及相容窗口假设下成立。没有重复扣月套餐免费量。</p><noscript><p>JavaScript 已禁用：初始示例为30天、Pro200、利用率50%、无额外重置、无其他费用；单位成本约0.0566。图形与证据仍完整可见。</p></noscript></section>
<section><h2>05 · 新增供应商套餐应填写什么？</h2><p class="muted">采购计划与已销售会员套餐分开。这里的输入只追加到当前页面的模拟列表，刷新即清空。</p><form id="planform"><div class="form"><label>对象名称<input id="planname" required placeholder="例如：新加坡主机套餐"></label><label>采购类型<select id="plantype"><option>服务器套餐</option><option>账号订阅</option><option>上游额度包</option></select></label><label>月费 / 原币<input id="planfee" required type="number" min="0" step=".01"></label><label>币种<select id="plancurrency"><option>USD</option><option>CNY</option></select></label><label>流量包含量 / GB<input id="plangb" type="number" min="0" placeholder="不适用留空"></label><label>流量口径<select id="plandirection"><option>仅出站</option><option>双向累计</option><option>按带宽：需独立规则</option></select></label></div><p><button type="submit">加入当前页面的模拟列表（不购买）</button></p></form><div id="plans" class="notes" aria-live="polite">尚未添加模拟套餐。</div><p class="notes">生产版本还须填：服务起止、账期时区、开服费、分期/摊销、阶梯超量价格、共享预算池、付款凭据与税费。仅填月费不等于完成账本。</p></section>
<section><h2>06 · 竞品价格和延迟：先比较口径，再比较数字</h2><div class="scroll"><table><thead><tr><th>来源 / 服务档</th><th>Sol 输入 / 输出（USD/百万）</th><th>公开延迟P50</th><th>公开吞吐P50</th><th>可信状态</th></tr></thead><tbody><tr><td>OpenAI 官方模型目录</td><td>4 / 20</td><td>未实测</td><td>未实测</td><td>参考价目</td></tr><tr><td>OpenRouter · OpenAI</td><td>2 / 10（索引显示促销）</td><td>4.98秒</td><td>42 token/秒</td><td>页面版本冲突，待核验</td></tr><tr><td>OpenRouter · OpenAI Flex</td><td>1 / 5（索引显示促销）</td><td>9.47秒</td><td>56 token/秒</td><td>不同服务档，不直接替代</td></tr></tbody></table></div><p class="notes">同页直接可读快照出现5/30，故促销与性能记录仅是候选证据，不能自动采购或改价。上述延迟由平台发布，不是从你的香港/新加坡链路测得的TTFT；两个Provider行也不意味着独立上游。</p></section>
<footer><strong>设计与验收边界</strong><p>基于 dev@507a820 · 只读研究分支；没有连接现网，没有运行生产Go/Vue构建，没有发布Pages。图形采用独立语义模型与静态导出，借鉴 Study_Skills learning-figure，但不声称通过其整套v2发布门禁。</p><p><a href="DESIGN.md">完整设计与来源</a> · <a href="../../tools/cost_research/public_snapshot.json">公开快照</a> · <a href="evidence-flow.svg">流程SVG</a> · <a href="refill-net-gain.svg">净增量SVG</a></p></footer></main>
<script>
const $=id=>document.getElementById(id);const preset={pro:[200,1649.72],pro5:[100,412.43],plus:[20,82.49]};
function calc(){const keys=['cash','days','base','use','events','remain','fixed','net'];const v={};let ok=true;keys.forEach(k=>{v[k]=Number($(k).value);ok=ok&&$(k).value!==''&&$(k).checkValidity()&&Number.isFinite(v[k]);});const q=v.days/7*v.base*v.use/100*(1+v.events*(1-v.remain/100));if(!ok||q<=0){$('unit').textContent='不可计算';$('detail').textContent='检查输入；有效交付为零时不能显示零成本。';return;}const c=v.cash+v.fixed+v.net;$('unit').textContent=(c/q).toFixed(4)+' USD';$('detail').textContent='模拟本期有效量 '+q.toLocaleString('zh-CN',{maximumFractionDigits:2})+'；成本'+c.toFixed(2)+' USD。不是每百万token价格。';}
$('tier').addEventListener('change',()=>{const p=preset[$('tier').value];$('cash').value=p[0];$('base').value=p[1];calc();});document.querySelectorAll('#sim input').forEach(x=>x.addEventListener('input',calc));
let n=0;$('planform').addEventListener('submit',event=>{event.preventDefault();if(!$('planform').reportValidity())return;if(!n)$('plans').textContent='';const row=document.createElement('p');row.textContent='模拟 '+(++n)+' · '+$('planname').value+' / '+$('plantype').value+' / '+$('planfee').value+' '+$('plancurrency').value+' 每月 / '+($('plangb').value||'未设')+' GB / '+$('plandirection').value;$('plans').appendChild(row);});
</script></body></html>'''
replacements={'@@FLOW@@':flow_svg,'@@MOBILE@@':mobile_flow,'@@REFILL@@':refill_svg,
'@@FLOW_TITLE@@':e(flow['question']),'@@FLOW_ORDER@@':e(flow['reading_order']),
'@@FLOW_TAKEAWAY@@':e(flow['takeaway']),'@@FLOW_BOUNDARY@@':e(flow['boundary']),
'@@REFILL_TITLE@@':e(refill['question']),'@@REFILL_TAKEAWAY@@':e(refill['takeaway']),
'@@REFILL_BOUNDARY@@':e(refill['boundary'])}
for key,value in replacements.items():html=html.replace(key,value)
(ROOT/'dashboard.html').write_text(html,encoding='utf-8')
print('Rendered dashboard.html, evidence-flow.svg, refill-net-gain.svg')
